Purpose: To perform checks on the data for a better chance at creating a robust algorithm

In [13]:
import pandas as pd
import json

In [15]:
valid_records = []
with open("payments.jsonl", "r", encoding="utf-8") as f:
    for line in f:
        line = line.strip()
        if not line:  # Skip empty lines
            continue
        try:
            valid_records.append(json.loads(line))
        except json.JSONDecodeError:
            continue  # Skips the malformed rows

In [16]:
df = pd.DataFrame(valid_records)
df.head()

            txn_id   status     amount currency                    ts
0  txn_017725_1862  success    3533.05      NGN  2026-09-21T15:30:26Z
1  txn_007794_1059   failed    12832.1      NGN  2026-09-21T04:38:46Z
2  txn_004559_9318  success  255767.69      NGN  2026-09-10T01:16:42Z
3  txn_002376_7469  success   42051.34      NGN  2026-09-16T22:13:25Z
4  txn_011930_1238   failed    1870.58      NGN  2026-09-16T04:03:00Z

In [ ]:
df_with_same_id = df[df.duplicated(subset=['txn_id'], keep="first")]
df[df["txn_id"] == "txn_007794_1059"]

               txn_id   status   amount currency                    ts
1     txn_007794_1059   failed  12832.1      NGN  2026-09-21T04:38:46Z
1833  txn_007794_1059  success  12832.1      NGN  2026-09-21T04:41:46Z

In [22]:
df["amount"].dtype

dtype('O')

In [26]:
# Check whether ts column values are not faulty 
df['ts'] = pd.to_datetime(df['ts'], format='ISO8601')
df['ts']

0       2026-09-21 15:30:26+00:00
1       2026-09-21 04:38:46+00:00
2       2026-09-10 01:16:42+00:00
3       2026-09-16 22:13:25+00:00
4       2026-09-16 04:03:00+00:00
                   ...
39692   2026-09-07 02:01:23+00:00
39693   2026-09-26 15:57:29+00:00
39694   2026-09-24 14:27:30+00:00
39695   2026-09-17 18:01:04+00:00
39696   2026-09-23 17:22:12+00:00
Name: ts, Length: 39697, dtype: datetime64[ns, UTC]

In [28]:
# Check whether there are txn_ids with no values
(df["txn_id"].str.strip() == '').any()

np.False_